import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Nota: Se elimina Geist_Mono para evitar precargas de woff2 no usadas
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: false, // mantenemos la variable sin precargar woff2
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en"  className="dark">
        <body
  className={`${geistSans.className} ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
      >
  {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
  


